### ISSUE TITLE
Office 2019 and Windows server 2019

### ISSUE THREAD

**Issue by johnripper1** [kebe7jun/linux-kms-server#2]
Will this Server work with Office 2019 and Windows Server 2019?

**Comment by jairov4** [comment]
I would like to know it too

**Comment by james-d-elliott** [comment]
According to a friend it did Server 2019. However I've not personally tested it.

**Comment by jairov4** [comment]
I tested, it works. feel free close the issue if needed

**Comment by kebe7jun** [comment]
@jairov4 Thanks!
@johnripper1 I'll close this issue.
